export const LOCAL_HELPER_AUDIO_SAMPLE_RATE = 16_000;
export const LOCAL_HELPER_CHUNK_OVERLAP_MS = 2_000;
export const LOCAL_HELPER_TARGET_CHUNK_SEC = 8 * 60;
export const LOCAL_HELPER_MIN_CHUNK_SEC = 90;
